version: '3.7'
services:
  app:
    build:
      context: .
      target: development
    ports:
      - '9090:5173'
    command: /bin/sh -c "while sleep 1000; do :; done"
    volumes:
      - ./:/app
